// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UfoFinal.Models;

#nullable disable

namespace UfoFinal.Migrations
{
    [DbContext(typeof(UfoContext))]
    [Migration("20221027172214_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("UfoFinal.Models.Observasjon", b =>
                {
                    b.Property<int>("ObservasjonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StedID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObservasjonID");

                    b.HasIndex("PersonID");

                    b.HasIndex("StedID");

                    b.ToTable("observasjoner");
                });

            modelBuilder.Entity("UfoFinal.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("Personer");
                });

            modelBuilder.Entity("UfoFinal.Models.Sted", b =>
                {
                    b.Property<int>("StedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("by")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("land")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StedID");

                    b.ToTable("Steder");
                });

            modelBuilder.Entity("UfoFinal.Models.Observasjon", b =>
                {
                    b.HasOne("UfoFinal.Models.Person", null)
                        .WithMany("Observasjoner")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UfoFinal.Models.Sted", null)
                        .WithMany("Observasjoner")
                        .HasForeignKey("StedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UfoFinal.Models.Person", b =>
                {
                    b.Navigation("Observasjoner");
                });

            modelBuilder.Entity("UfoFinal.Models.Sted", b =>
                {
                    b.Navigation("Observasjoner");
                });
#pragma warning restore 612, 618
        }
    }
}
